spring:
  application:
    name: Онлайн магазин
  profiles:
    active: actuator, swagger

server:
  port: 8071
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

shop:
  registration:
    type: phone