POST http://localhost:8071/api/registration
Content-Type: application/json

{
  "username": "123"
}

###

# curl -X POST --location "http://localhost:8071/hello" -H "Content-Type: application/json"  -d '{"username": "123" }'

###

